Hw 21
KrohIgor/internet-shop pull request #11
Opened 2020-05-09 06:55 UTC by KrohIgor

2020-05-10 11:24 UTC, boroda4436 requested changes

2020-05-10 11:24 UTC, boroda4436 commented on src/main/java/mate/academy/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +                String productName = resultSet.getString("productname");
code duplication on line 43

2020-05-10 11:24 UTC, boroda4436 commented on src/main/java/mate/academy/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            throw new DataProcessingException();
```suggestion
            throw new DataProcessingException(e);
```
Do not lose helpful info, re throw the exception

2020-05-10 11:24 UTC, boroda4436 commented on src/main/java/mate/academy/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            throw new DataProcessingException();
```suggestion
            throw new DataProcessingException(e);
```

2020-05-10 11:24 UTC, boroda4436 commented on src/main/java/mate/academy/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            throw new DataProcessingException();
```suggestion
            throw new DataProcessingException(e);
```

2020-05-10 11:24 UTC, boroda4436 commented on src/main/java/mate/academy/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            throw new DataProcessingException();
```suggestion
            throw new DataProcessingException(e);
```

2020-05-11 14:40 UTC, KrohIgor commented on src/main/java/mate/academy/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +                String productName = resultSet.getString("productname");
take out in a separate method

2020-05-11 14:43 UTC, KrohIgor commented on src/main/java/mate/academy/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            throw new DataProcessingException();
done

2020-05-11 14:43 UTC, KrohIgor commented on src/main/java/mate/academy/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            throw new DataProcessingException();
done

2020-05-11 14:43 UTC, KrohIgor commented on src/main/java/mate/academy/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            throw new DataProcessingException();
done

2020-05-11 14:43 UTC, KrohIgor commented on src/main/java/mate/academy/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            throw new DataProcessingException();
done

2020-05-12 08:34 UTC, dmytro-hryhoruk approved these changes

2020-05-12 08:34 UTC, dmytro-hryhoruk commented on src/main/java/mate/academy/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            throw new DataProcessingException(e);
also it's better to add custom message throw new DataProcessingException("Couldn't get Product with id - " + id,  e);

2020-05-12 08:34 UTC, dmytro-hryhoruk commented on src/main/resources/init_db.sql
> +  PRIMARY KEY (`product_id`));
empty line

2020-05-12 08:55 UTC, KrohIgor commented on src/main/java/mate/academy/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            throw new DataProcessingException(e);
done

2020-05-12 08:56 UTC, KrohIgor commented on src/main/resources/init_db.sql
> +  PRIMARY KEY (`product_id`));
done

2020-05-12 09:06 UTC, merged